-- MySQL Script generated by MySQL Workbench
-- Sat Nov 15 10:26:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aerolinea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aerolinea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aerolinea` DEFAULT CHARACTER SET utf8 ;
USE `aerolinea` ;

-- -----------------------------------------------------
-- Table `aerolinea`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL UNIQUE,
  `clave` VARCHAR(45) NOT NULL,
  `img_perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;

INSERT INTO `admin` ( `nombre`, `apellido`, `correo`, `clave`, `img_perfil`) VALUES
( 'Jonathan', 'Bernal', 'asd@aero.com', '202cb962ac59075b964b07152d234b70', 'no hay');
-- -----------------------------------------------------
-- Table `aerolinea`.`Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Piloto` (
  `idPiloto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL UNIQUE,
  `clave` VARCHAR(45) NOT NULL,
  `img_piloto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPiloto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Pasajero` (
  `idPasajero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL UNIQUE,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPasajero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_Ciudad_Pais1_idx` (`Pais_idPais` ASC),
  CONSTRAINT `fk_Ciudad_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `aerolinea`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Aviones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Aviones` (
  `idAviones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`idAviones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Ruta` (
  `idRuta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  `Ciudad_idCiudad1` INT NOT NULL,
  PRIMARY KEY (`idRuta`),
  INDEX `fk_Ruta_Ciudad1_idx` (`Ciudad_idCiudad` ASC),
  INDEX `fk_Ruta_Ciudad2_idx` (`Ciudad_idCiudad1` ASC),
  CONSTRAINT `fk_Ruta_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `aerolinea`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ruta_Ciudad2`
    FOREIGN KEY (`Ciudad_idCiudad1`)
    REFERENCES `aerolinea`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Vuelo` (
  `idVuelo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` DATETIME NOT NULL,
  `Piloto_idPiloto` INT NOT NULL,
  `Piloto_idPiloto1` INT NOT NULL,
  `Aeropuerto_idAeropuerto` INT NOT NULL,
  `Aeropuerto_idAeropuerto1` INT NOT NULL,
  `Aviones_idAviones` INT NOT NULL,
  `Ruta_idRuta` INT NOT NULL,
  PRIMARY KEY (`idVuelo`),
  INDEX `fk_Vuelo_Piloto_idx` (`Piloto_idPiloto` ASC),
  INDEX `fk_Vuelo_Piloto1_idx` (`Piloto_idPiloto1` ASC),
  INDEX `fk_Vuelo_Aviones1_idx` (`Aviones_idAviones` ASC),
  INDEX `fk_Vuelo_Ruta1_idx` (`Ruta_idRuta` ASC),
  CONSTRAINT `fk_Vuelo_Piloto`
    FOREIGN KEY (`Piloto_idPiloto`)
    REFERENCES `aerolinea`.`Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_Piloto1`
    FOREIGN KEY (`Piloto_idPiloto1`)
    REFERENCES `aerolinea`.`Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_Aviones1`
    FOREIGN KEY (`Aviones_idAviones`)
    REFERENCES `aerolinea`.`Aviones` (`idAviones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_Ruta1`
    FOREIGN KEY (`Ruta_idRuta`)
    REFERENCES `aerolinea`.`Ruta` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Pasajero_has_Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Pasajero_has_Vuelo` (
  `Pasajero_idPasajero` INT NOT NULL,
  `Vuelo_idVuelo` INT NOT NULL,
  `cant_personas` INT NOT NULL,
  PRIMARY KEY (`Pasajero_idPasajero`, `Vuelo_idVuelo`),
  INDEX `fk_Pasajero_has_Vuelo_Vuelo1_idx` (`Vuelo_idVuelo` ASC),
  INDEX `fk_Pasajero_has_Vuelo_Pasajero1_idx` (`Pasajero_idPasajero` ASC),
  CONSTRAINT `fk_Pasajero_has_Vuelo_Pasajero1`
    FOREIGN KEY (`Pasajero_idPasajero`)
    REFERENCES `aerolinea`.`Pasajero` (`idPasajero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasajero_has_Vuelo_Vuelo1`
    FOREIGN KEY (`Vuelo_idVuelo`)
    REFERENCES `aerolinea`.`Vuelo` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
