-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 15:41:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aerolinea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aerolinea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aerolinea` DEFAULT CHARACTER SET utf8 ;
USE `aerolinea` ;

-- -----------------------------------------------------
-- Table `aerolinea`.`P3Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `img_perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`P3Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`P3Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `P3Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_P3Ciudad_P3Pais1_idx` (`P3Pais_idPais` ASC),
  CONSTRAINT `fk_P3Ciudad_P3Pais1`
    FOREIGN KEY (`P3Pais_idPais`)
    REFERENCES `aerolinea`.`P3Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`Piloto` (
  `idPiloto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `img_piloto` VARCHAR(45) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  `P3Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idPiloto`),
  INDEX `fk_Piloto_P3Ciudad1_idx` (`P3Ciudad_idCiudad` ASC),
  CONSTRAINT `fk_Piloto_P3Ciudad1`
    FOREIGN KEY (`P3Ciudad_idCiudad`)
    REFERENCES `aerolinea`.`P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`P3Pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Pasajero` (
  `idPasajero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPasajero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`P3Aviones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Aviones` (
  `idAviones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `P3Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idAviones`),
  INDEX `fk_P3Aviones_P3Ciudad1_idx` (`P3Ciudad_idCiudad` ASC),
  CONSTRAINT `fk_P3Aviones_P3Ciudad1`
    FOREIGN KEY (`P3Ciudad_idCiudad`)
    REFERENCES `aerolinea`.`P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`P3Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Ruta` (
  `idRuta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `P3Ciudad_idCiudad` INT NOT NULL,
  `P3Ciudad_idCiudad1` INT NOT NULL,
  PRIMARY KEY (`idRuta`),
  INDEX `fk_P3Ruta_P3Ciudad1_idx` (`P3Ciudad_idCiudad` ASC),
  INDEX `fk_P3Ruta_P3Ciudad2_idx` (`P3Ciudad_idCiudad1` ASC),
  CONSTRAINT `fk_P3Ruta_P3Ciudad1`
    FOREIGN KEY (`P3Ciudad_idCiudad`)
    REFERENCES `aerolinea`.`P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Ruta_P3Ciudad2`
    FOREIGN KEY (`P3Ciudad_idCiudad1`)
    REFERENCES `aerolinea`.`P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`P3Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Vuelo` (
  `idVuelo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` DATETIME NOT NULL,
  `Piloto_idPiloto1` INT NOT NULL,
  `Aeropuerto_idAeropuerto` INT NOT NULL,
  `Aeropuerto_idAeropuerto1` INT NOT NULL,
  `P3Ruta_idRuta` INT NOT NULL,
  `P3Aviones_idAviones` INT NOT NULL,
  `Piloto_idPiloto` INT NOT NULL,
  PRIMARY KEY (`idVuelo`),
  INDEX `fk_Vuelo_Piloto1_idx` (`Piloto_idPiloto1` ASC),
  INDEX `fk_P3Vuelo_P3Ruta1_idx` (`P3Ruta_idRuta` ASC),
  INDEX `fk_P3Vuelo_P3Aviones1_idx` (`P3Aviones_idAviones` ASC),
  INDEX `fk_P3Vuelo_Piloto1_idx` (`Piloto_idPiloto` ASC),
  CONSTRAINT `fk_Vuelo_Piloto1`
    FOREIGN KEY (`Piloto_idPiloto1`)
    REFERENCES `aerolinea`.`Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_P3Ruta1`
    FOREIGN KEY (`P3Ruta_idRuta`)
    REFERENCES `aerolinea`.`P3Ruta` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_P3Aviones1`
    FOREIGN KEY (`P3Aviones_idAviones`)
    REFERENCES `aerolinea`.`P3Aviones` (`idAviones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_Piloto1`
    FOREIGN KEY (`Piloto_idPiloto`)
    REFERENCES `aerolinea`.`Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aerolinea`.`P3Pasajero_has_P3Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aerolinea`.`P3Pasajero_has_P3Vuelo` (
  `P3Pasajero_idPasajero` INT NOT NULL,
  `P3Vuelo_idVuelo` INT NOT NULL,
  `cantPersonas` INT NOT NULL,
  `calTripulacion` INT NOT NULL,
  `calAvion` INT NOT NULL,
  PRIMARY KEY (`P3Pasajero_idPasajero`, `P3Vuelo_idVuelo`),
  INDEX `fk_P3Pasajero_has_P3Vuelo_P3Vuelo1_idx` (`P3Vuelo_idVuelo` ASC),
  INDEX `fk_P3Pasajero_has_P3Vuelo_P3Pasajero1_idx` (`P3Pasajero_idPasajero` ASC),
  CONSTRAINT `fk_P3Pasajero_has_P3Vuelo_P3Pasajero1`
    FOREIGN KEY (`P3Pasajero_idPasajero`)
    REFERENCES `aerolinea`.`P3Pasajero` (`idPasajero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Pasajero_has_P3Vuelo_P3Vuelo1`
    FOREIGN KEY (`P3Vuelo_idVuelo`)
    REFERENCES `aerolinea`.`P3Vuelo` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
