-- MySQL Script generated by MySQL Workbench
-- Tue Dec  2 20:46:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table  `P3Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `P3Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_P3Ciudad_P3Pais1_idx` (`P3Pais_idPais` ASC)  ,
  CONSTRAINT `fk_P3Ciudad_P3Pais1`
    FOREIGN KEY (`P3Pais_idPais`)
    REFERENCES  `P3Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Piloto` (
  `idPiloto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  `fechaActivacion` DATE NOT NULL,
  `P3UbicacionActual` INT NOT NULL,
  PRIMARY KEY (`idPiloto`),
  INDEX `fk_Piloto_P3Ciudad1_idx` (`P3UbicacionActual` ASC)  ,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC)  ,
  CONSTRAINT `fk_Piloto_P3Ciudad1`
    FOREIGN KEY (`P3UbicacionActual`)
    REFERENCES  `P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Pasajero` (
  `NroCedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `estado` TINYINT NOT NULL,
  `fechaActivacion` DATE NULL,
  PRIMARY KEY (`NroCedula`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Avion` (
  `idAviones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `P3UbicacionActual` INT NOT NULL,
  PRIMARY KEY (`idAviones`),
  INDEX `fk_P3Aviones_P3Ciudad1_idx` (`P3UbicacionActual` ASC)  ,
  CONSTRAINT `fk_P3Aviones_P3Ciudad1`
    FOREIGN KEY (`P3UbicacionActual`)
    REFERENCES  `P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Ruta` (
  `idRuta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `P3CiudadOrigen` INT NOT NULL,
  `P3CiudadDestino` INT NOT NULL,
  PRIMARY KEY (`idRuta`),
  INDEX `fk_P3Ruta_P3Ciudad1_idx` (`P3CiudadOrigen` ASC)  ,
  INDEX `fk_P3Ruta_P3Ciudad2_idx` (`P3CiudadDestino` ASC)  ,
  CONSTRAINT `fk_P3Ruta_P3Ciudad1`
    FOREIGN KEY (`P3CiudadOrigen`)
    REFERENCES  `P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Ruta_P3Ciudad2`
    FOREIGN KEY (`P3CiudadDestino`)
    REFERENCES  `P3Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3EstadoVuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3EstadoVuelo` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Vuelo` (
  `idVuelo` INT NOT NULL AUTO_INCREMENT,
  `fechaHoraLlegada` DATETIME NULL,
  `fechaHoraSalida` DATETIME NOT NULL,
  `P3Ruta_idRuta` INT NOT NULL,
  `P3Aviones_idAviones` INT NOT NULL,
  `P3Copiloto` INT NOT NULL,
  `P3Piloto` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idVuelo`),
  INDEX `fk_Vuelo_Piloto1_idx` (`P3Copiloto` ASC)  ,
  INDEX `fk_P3Vuelo_P3Ruta1_idx` (`P3Ruta_idRuta` ASC)  ,
  INDEX `fk_P3Vuelo_P3Aviones1_idx` (`P3Aviones_idAviones` ASC)  ,
  INDEX `fk_P3Vuelo_Piloto1_idx` (`P3Piloto` ASC)  ,
  INDEX `fk_P3Vuelo_Estado1_idx` (`Estado_idEstado` ASC)  ,
  CONSTRAINT `fk_Vuelo_Piloto1`
    FOREIGN KEY (`P3Copiloto`)
    REFERENCES  `P3Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_P3Ruta1`
    FOREIGN KEY (`P3Ruta_idRuta`)
    REFERENCES  `P3Ruta` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_P3Aviones1`
    FOREIGN KEY (`P3Aviones_idAviones`)
    REFERENCES  `P3Avion` (`idAviones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_Piloto1`
    FOREIGN KEY (`P3Piloto`)
    REFERENCES  `P3Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES  `P3EstadoVuelo` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `P3Pasajero_NroCedula` INT NOT NULL,
  `cantTiquetes` INT NOT NULL,
  `precioTiquete` INT NOT NULL,
  `fechaReserva` DATETIME NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_P3Pasajero_has_P3Vuelo1_P3Pasajero1_idx` (`P3Pasajero_NroCedula` ASC)  ,
  CONSTRAINT `fk_P3Pasajero_has_P3Vuelo1_P3Pasajero1`
    FOREIGN KEY (`P3Pasajero_NroCedula`)
    REFERENCES  `P3Pasajero` (`NroCedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Asiento` (
  `idAsiento` INT NOT NULL AUTO_INCREMENT,
  `precio` INT NOT NULL,
  `P3Vuelo_idVuelo` INT NOT NULL,
  PRIMARY KEY (`idAsiento`),
  INDEX `fk_P3Asiento_P3Vuelo1_idx` (`P3Vuelo_idVuelo` ASC)  ,
  CONSTRAINT `fk_P3Asiento_P3Vuelo1`
    FOREIGN KEY (`P3Vuelo_idVuelo`)
    REFERENCES  `P3Vuelo` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3ReservaAsiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3ReservaAsiento` (
  `P3Reserva_idReserva` INT NOT NULL,
  `P3Asiento_idAsiento` INT NOT NULL,
  PRIMARY KEY (`P3Reserva_idReserva`, `P3Asiento_idAsiento`),
  INDEX `fk_P3Reserva_has_P3Asiento_P3Asiento1_idx` (`P3Asiento_idAsiento` ASC)  ,
  INDEX `fk_P3Reserva_has_P3Asiento_P3Reserva1_idx` (`P3Reserva_idReserva` ASC)  ,
  UNIQUE INDEX `P3Asiento_idAsiento_UNIQUE` (`P3Asiento_idAsiento` ASC)  ,
  CONSTRAINT `fk_P3Reserva_has_P3Asiento_P3Reserva1`
    FOREIGN KEY (`P3Reserva_idReserva`)
    REFERENCES  `P3Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Reserva_has_P3Asiento_P3Asiento1`
    FOREIGN KEY (`P3Asiento_idAsiento`)
    REFERENCES  `P3Asiento` (`idAsiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Tiquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Tiquete` (
  `idTiquete` INT NOT NULL AUTO_INCREMENT,
  `precio` INT NOT NULL,
  `P3ReservaAsiento_P3Reserva_idReserva` INT NOT NULL,
  `P3ReservaAsiento_P3Asiento_idP3Asiento` INT NOT NULL,
  PRIMARY KEY (`idTiquete`),
  INDEX `fk_P3Tiquete_P3ReservaAsiento1_idx` (`P3ReservaAsiento_P3Reserva_idReserva` ASC, `P3ReservaAsiento_P3Asiento_idP3Asiento` ASC)  ,
  CONSTRAINT `fk_P3Tiquete_P3ReservaAsiento1`
    FOREIGN KEY (`P3ReservaAsiento_P3Reserva_idReserva` , `P3ReservaAsiento_P3Asiento_idP3Asiento`)
    REFERENCES  `P3ReservaAsiento` (`P3Reserva_idReserva` , `P3Asiento_idAsiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3CheckIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3CheckIn` (
  `idCheckIn` INT NOT NULL AUTO_INCREMENT,
  `fechaHoraCheckIn` DATETIME NOT NULL,
  `P3Tiquete_idTiquete` INT NOT NULL,
  PRIMARY KEY (`idCheckIn`),
  INDEX `fk_P3CheckIn_P3Tiquete1_idx` (`P3Tiquete_idTiquete` ASC)  ,
  CONSTRAINT `fk_P3CheckIn_P3Tiquete1`
    FOREIGN KEY (`P3Tiquete_idTiquete`)
    REFERENCES  `P3Tiquete` (`idTiquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `P3Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `P3Calificacion` (
  `P3Vuelo_idVuelo` INT NOT NULL,
  `P3Pasajero_NroCedula` INT NOT NULL,
  `calTripulacion` INT NULL,
  `calAvion` INT NULL,
  PRIMARY KEY (`P3Vuelo_idVuelo`, `P3Pasajero_NroCedula`),
  INDEX `fk_P3Vuelo_has_P3Pasajero_P3Pasajero1_idx` (`P3Pasajero_NroCedula` ASC)  ,
  INDEX `fk_P3Vuelo_has_P3Pasajero_P3Vuelo1_idx` (`P3Vuelo_idVuelo` ASC)  ,
  CONSTRAINT `fk_P3Vuelo_has_P3Pasajero_P3Vuelo1`
    FOREIGN KEY (`P3Vuelo_idVuelo`)
    REFERENCES  `P3Vuelo` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P3Vuelo_has_P3Pasajero_P3Pasajero1`
    FOREIGN KEY (`P3Pasajero_NroCedula`)
    REFERENCES  `P3Pasajero` (`NroCedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
